version: '3.8'

services:
  db:
    container_name: mysql_db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
        # So you don't have to use root, but you can if you like
      MYSQL_USER: ${DB_USERNAME}
        # You can use whatever password you like
      MYSQL_PASSWORD: ${DB_PASSWORD}
        # Password for root access
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - ${DB_PORT}:${DB_PORT}
    expose:
      # Opens port 3306 on the container
      - ${DB_PORT}
   # Where our data will be persisted
    volumes:
      - ./dbdata:/var/lib/mysql